config {
    type: 'incremental',
    schema: 'mbta',
    name: 'bronze_routes',
    tags: ['mbta'],
    protected: true,
    hermetic: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions.buildDesertBronze('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
