config {
    type: 'incremental',
    schema: 'silver',
    name: 'alerts_cleaned',
    dependencies: ['alerts_raw'],
    tags: ['alerts'],
    protected: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions_silver.buildDesertSilver('alerts');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
