config {
    type: 'incremental',
    schema: 'silver',
    name: 'alerts_cleaned',
    dependencies: ['alerts_raw'],
    tags: ['mbta']
}

js {
    const {
        deleteStatement,
        selectStatement
    } = functions_silver.buildDesertSilver('alerts');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${selectStatement}
    ${
        when(
            incremental(),
            deleteStatement
        )
    }
}
