config {
    type: 'incremental',
    schema: 'silver',
    name: 'routes_cleaned',
    dependencies: ['routes_raw'],
    tags: ['routes'],
    protected: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions_silver.buildDesertSilver('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
