config {
    type: 'incremental',
    schema: 'silver',
    name: 'routes_cleaned',
    dependencies: ['routes_raw'],
    tags: ['mbta']
}

js {
    const {
        deleteStatement,
        selectStatement
    } = functions_silver.buildDesertSilver('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${selectStatement}
    ${
        when(
            incremental(),
            deleteStatement
        )
    }
}
