config {
    type: 'incremental',
    schema: 'silver',
    name: 'shapes_cleaned',
    tags: ['shapes'],
    dependencies: ['shapes_raw'],
    protected: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions_silver.buildDesertSilver('shapes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
