config {
    type: 'incremental',
    schema: 'gold',
    name: 'system_alerts',
    dependencies: [
        'alerts_cleaned',
        'routes_cleaned'
    ],
    tags: ['mbta']
}

js {
    const {
        deleteStatement,
        selectStatement
    } = functions.desertSystemAlerts();
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${selectStatement}
    ${
        when(
            incremental(),
            deleteStatement
        )
    }
}
