config {
    type: 'incremental',
    schema: 'silver',
    name: 'alerts_enriched',
    dependencies: [
        'alerts_raw',
        'routes_raw'
    ],
    tags: ['mbta']
}

js {
    const {
        deleteStatement,
        selectStatement
    } = functions.desertS1();
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${selectStatement}
    ${
        when(
            incremental(),
            deleteStatement
        )
    }
}
