config {
    type: 'incremental',
    schema: 'bronze',
    name: 'alerts_raw',
    tags: ['mbta'],
    protected: true
}

js {
    const {
        deleteStatement,
        selectStatement
    } = functions_bronze.buildDesertBronze('alerts');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${selectStatement}
    ${
        when(
            incremental(),
            deleteStatement
        )
    }
}
