config {
    type: 'incremental',
    dataset: 'mbta',
    name: 'bronze_alerts',
    tags: ['alerts'],
    protected: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions.buildDesertBronze('alerts');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
