config {
    type: 'incremental',
    dataset: 'mbta',
    name: 'silver_routes',
    tags: ['routes'],
    dependencies: [{
        dataset: 'routes',
        name: 'bronze'
    }]
}

js {
    const {
        delete_statement,
        select_statement
    } = functions.buildDesertSilver('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
