config {
    type: 'incremental',
    schema: 'routes',
    name: 'bronze',
    tags: ['routes'],
    protected: true
}

js {
    const {
        delete_statement,
        select_statement
    } = functions.buildDesertBronze('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
