config {
    type: 'incremental',
    schema: 'routes',
    name: 'routes_silver',
    tags: ['routes'],
    dependencies: ['routes_bronze']
}

js {
    const {
        delete_statement,
        select_statement
    } = functions.buildDesertSilver('routes');
}

SELECT
  *
FROM
  TEMP

pre_operations {
  CREATE TEMP TABLE TEMP AS ${select_statement}
    ${
        when(
            incremental(),
            delete_statement
        )
    }
}
