name: 'mbta_reliability_analytics'  # project name for this dbt project
version: '1.0.0'  # project version
config-version: 2  # dbt config version

# Profile to use for dbt runs
profile: 'mbta_reliability_analytics'

# File and folder locations
model-paths: ["models"]  # where dbt models are stored
# analysis-paths: ["analyses"]  # (optional) where analysis files are stored
test-paths: ["tests"]  # where dbt tests are stored
# seed-paths: ["seeds"]  # (optional) where seed files are stored
macro-paths: ["macros"]  # where dbt macros are stored
# snapshot-paths: ["snapshots"]  # (optional) where snapshots are stored

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"  # dbt build artifacts
  - "dbt_packages"  # dbt package dependencies

# Post-run cleanup hook
on-run-end:
  - "{{ drop_temp_tables() }}"  # custom macro to drop temp tables

# Model configuration
# See: https://docs.getdbt.com/docs/configuring-models
